name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Install dependencies
        run: yarn

      - name: Build and Pack distribution package
        run: yarn run package
        env:
          NODE_ENV: production
          DEBUG: "electron-forge:*"
