name: publish

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "15"

      - name: Install dependencies
        run: yarn

      - name: Build / Publish application
        run: yarn run publish
        env:
          NODE_ENV: production
          DEBUG: "electron-forge:*"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
